#!/usr/bin/python
import os
import sys

sys.path.insert(0, os.path.dirname(__file__) or '.')
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)) or '.')

from flaskapp import app as application
